name: deploy-prod
on:
 workflow_dispatch:
    inputs:
      deploy_prod:
        type: string
        default: ''
        required: false 
jobs:
 GetData:
  runs-on: ubuntu-latest
  steps:
   - name: Docker Build
     run: |
      echo "Doing docker build ${{ github.ref }}, ${{ github.event_name }}, ${{ github.event.action }}, ${{ github.event.inputs.deploy_prod }}" 
      sleep 5
      docker images
      echo "Docker done"
      
 deploy-prod:
  runs-on: ubuntu-latest
  if: |
   (github.ref == 'refs/heads/main' && 
    github.event.name == 'workflow_dispatch' &&
    github.event.inputs.deploy_prod == 'manual')
  steps:
   - name: Deploy Prod
     run: |
      echo "Deploying to Prod env."
      sleep 5
      echo "Deploying to Prod env. done"
 
