name: CI
on:
 push:
 
jobs:
 varibaleSetting:
  name: "setting env"
  runs-on: ubuntu-latest
  strategy:
   matrix:
    env1: [test, qa]
  outputs:
   env1: ${{ matrix.env1 }}
  steps:
   - name: setting env variables
     run: |
      echo "Setting env variables ${{ matrix.env1 }}"
   
   - name: Checkout repo
     uses: actions/checkout@v3
     with:
      fetch-depth: 50
      lfs: true
        
   - name: Run git config. 
     run: |
      #git config user.email "actions@github.com"
      #git config user.name "GitHub Actions"
      #.git_template: &git_setup |
      git remote set-url --push origin "https://github.com/shrikantbhadane/test.git"
      git config user.name "INDIGO Github CI"
      git config user.email indigo@bayer.github.com
      git status
      git config --list
      echo ${{ github.repositoryUrl }}
      echo ${{ github.server_url }}
      echo ${{ github.repository }}
                 
 #callingReusable:
  #needs: varibaleSetting
  #name: "calling reusable workflow"
  #runs-on: ubuntu-latest
  #steps:
  # - run: echo " from callingReusable ${{ needs.varibaleSetting.outputs.env1 }}"
  #uses: ./.github/workflows/reusable.yml
  #with:
  # env2: ${{ needs.varibaleSetting.outputs.env1 }}

