name: CI
on:
 push:
 workflow_dispatch:
    inputs:
      test:
        type: string
        default: ''
        required: false
jobs:
 varibaleSetting:
  name: "setting env"
  runs-on: ubuntu-latest
  #if: github.run_attempt == 1
  #if: github.event_name != 'workflow_dispatch' #&& github.event.inputs.test == 'manual'
  strategy:
   matrix:
    env1: [test, qa]
  outputs:
   env1: ${{ matrix.env1 }}
  steps:
   - name: setting env variables
     run: |
      echo "Setting env variables ${{ matrix.env1 }}"
   
   - name: Checkout repo
     uses: actions/checkout@v3
     with:
      fetch-depth: 50
      lfs: true
        
   - name: Run git config. 
     run: |
      echo ${{ github.repositoryUrl }}
      echo ${{ github.server_url }}
      echo ${{ github.repository }}
      echo git remote set-url --push origin "${{ github.server_url }}/${{ github.repository }}.git"
      echo "github-run-id=${{ github.run_id }}"
      echo "github-run-number=${{ github.run_number }}"
  
 testjob:
  name: testjob
  needs: varibaleSetting
  runs-on: ubuntu-latest
  if: success()
  steps:
   - name: Test another job
     if: github.event_name == 'workflow_dispatch' # && github.event.inputs.test == 'manual'
     run: echo " I am running with github attempt ${{ github.run_attempt }}"
 #callingReusable:
  #needs: varibaleSetting
  #name: "calling reusable workflow"
  #runs-on: ubuntu-latest
  #steps:
  # - run: echo " from callingReusable ${{ needs.varibaleSetting.outputs.env1 }}"
  #uses: ./.github/workflows/reusable.yml
  #with:
  # env2: ${{ needs.varibaleSetting.outputs.env1 }}

