name: CI
on:
 push:
 
jobs:
 varibaleSetting:
  name: "setting env"
  runs-on: ubuntu-latest
  strategy:
   matrix:
    env1: [test, qa]
  outputs:
   env1: ${{ matrix.env1 }}
  steps:
   - name: setting env variables
     run: |
      echo "Setting env variables ${{ matrix.env1 }}"
   
 callingReusable:
  needs: varibaleSetting
  name: "calling reusable workflow"
  #runs-on: ubuntu-latest
  #steps:
  # - run: echo " from callingReusable ${{ needs.varibaleSetting.outputs.env1 }}"
  uses: ./.github/workflows/reusable.yml
  with:
   env2: ${{ needs.varibaleSetting.outputs.env1 }}
